# Generated by Django 5.0.6 on 2024-07-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Worker',
        ),
        migrations.RemoveField(
            model_name='category',
            name='location',
        ),
        migrations.RemoveField(
            model_name='category',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='category',
            name='smallDesc',
        ),
        migrations.AddField(
            model_name='category',
            name='workers',
            field=models.ManyToManyField(related_name='categories', to='base.worker'),
        ),
    ]
