# Generated by Django 5.0.6 on 2024-07-15 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_category_worker_remove_category_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='price',
            new_name='pricePerHour',
        ),
        migrations.RemoveField(
            model_name='category',
            name='workers',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='skills',
        ),
        migrations.AddField(
            model_name='worker',
            name='categories',
            field=models.ManyToManyField(related_name='workers', to='base.category'),
        ),
        migrations.AddField(
            model_name='worker',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='worker',
            name='small_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issued_by', models.CharField(max_length=255)),
                ('date_issued', models.DateField()),
                ('workers', models.ManyToManyField(related_name='certificates_set', to='base.worker')),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='certificates',
            field=models.ManyToManyField(blank=True, to='base.certificate'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('year_completed', models.IntegerField()),
                ('workers', models.ManyToManyField(related_name='educations_set', to='base.worker')),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='educations',
            field=models.ManyToManyField(blank=True, to='base.education'),
        ),
        migrations.CreateModel(
            name='ExtraImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='extra_images/')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images_set', to='base.worker')),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='extra_images',
            field=models.ManyToManyField(blank=True, related_name='related_workers', to='base.extraimage'),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('workers', models.ManyToManyField(related_name='languages_set', to='base.worker')),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='languages',
            field=models.ManyToManyField(blank=True, to='base.language'),
        ),
    ]
