# Generated by Django 5.0.6 on 2024-07-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
