# Generated by Django 5.0.6 on 2024-07-16 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_worker_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='extra_images',
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='base.worker'),
        ),
    ]
