# Generated by Django 5.0.6 on 2024-07-16 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_worker_extra_images_alter_extraimage_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='workers',
        ),
        migrations.RemoveField(
            model_name='education',
            name='workers',
        ),
        migrations.RemoveField(
            model_name='language',
            name='workers',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='educations',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='languages',
        ),
        migrations.AddField(
            model_name='certificate',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='base.worker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='worker',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='base.worker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='worker',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='base.worker'),
            preserve_default=False,
        ),
    ]
