# Generated by Django 5.0.6 on 2024-07-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_certificate_workers_remove_education_workers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to='base.worker'),
        ),
        migrations.AddField(
            model_name='worker',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=2, max_length=1),
            preserve_default=False,
        ),
    ]
