# Generated by Django 5.0.6 on 2024-07-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_category_participants_worker_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='faBroom', max_length=255),
        ),
    ]
