# Generated by Django 5.0.6 on 2024-07-23 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_category_image_url_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='participants',
        ),
    ]
