# Generated by Django 5.0.6 on 2024-08-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_worker_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='cover_photo',
            field=models.ImageField(blank=True, default='cover_photos/placeholder.png', null=True, upload_to='cover_photos/'),
        ),
    ]
