# Generated by Django 5.0.6 on 2024-08-01 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_worker_cover_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='cover_photo',
        ),
    ]
