# Generated by Django 5.0.6 on 2024-08-05 10:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_review_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='year_completed',
        ),
        migrations.AddField(
            model_name='education',
            name='date_ended',
            field=models.DateTimeField(default='2024-08-05 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='date_started',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
