# Generated by Django 5.0.6 on 2024-08-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_education_year_completed_education_date_ended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('arabe', 'العربية'), ('francais', 'Français'), ('english', 'English')], max_length=50),
        ),
    ]
