# Generated by Django 5.0.6 on 2024-08-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_worker_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
