# Generated by Django 5.0.6 on 2024-08-07 15:34

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_worker_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='num_tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
