# Generated by Django 5.0.6 on 2024-08-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_worker_num_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='pricePerHour',
            new_name='price',
        ),
        migrations.AddField(
            model_name='worker',
            name='payment_type',
            field=models.CharField(choices=[('PH', 'Per Hour'), ('PM', 'Per Mission'), ('CS', 'Custom Specification')], default='PH', max_length=2),
        ),
    ]
