# Generated by Django 5.0.6 on 2024-08-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_rename_priceperhour_worker_price_worker_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='custom_payment_specification',
            field=models.TextField(blank=True, help_text="Specify if 'Custom Specification' is selected.", null=True),
        ),
    ]
