# Generated by Django 5.0.6 on 2024-08-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_worker_custom_payment_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='custom_payment_specification',
        ),
        migrations.AlterField(
            model_name='worker',
            name='payment_type',
            field=models.CharField(choices=[('PH', 'Per Hour'), ('PM', 'Per Mission')], default='PH', max_length=2),
        ),
    ]
