# Generated by Django 5.0.6 on 2024-08-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_worker_custom_payment_specification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='payment_type',
            field=models.CharField(choices=[('Per Hour', 'Per Hour'), ('Per Missions', 'Per Mission')], default='PH', max_length=12),
        ),
    ]
