# Generated by Django 5.0.6 on 2024-08-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_worker_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='payment_type',
            field=models.CharField(choices=[('Per Hour', 'Per Hour'), ('Per Mission', 'Per Mission')], default='PH', max_length=12),
        ),
    ]
