# Generated by Django 5.0.6 on 2024-08-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_jobcomment_num_tel_jobcomment_payment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcomment',
            name='num_tel',
        ),
        migrations.RemoveField(
            model_name='jobcomment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='jobcomment',
            name='tools_needed',
        ),
    ]
