# Generated by Django 5.0.6 on 2024-08-14 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_rename_extraimage_workerextraimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerextraimage',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.worker'),
        ),
    ]
