# Generated by Django 5.0.6 on 2024-08-14 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_workerextraimage_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerextraimage',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='base.worker'),
        ),
    ]
