# Generated by Django 5.0.6 on 2024-08-16 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_workerextraimage_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobextraimage',
            name='image',
            field=models.ImageField(upload_to='job/extra_images/'),
        ),
        migrations.AlterField(
            model_name='jobextraimage',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_extra_images', to='base.job'),
        ),
    ]
