// constants/jobConstants.js
export const JOB_DETAILS_REQUEST = 'JOB_DETAILS_REQUEST';
export const JOB_DETAILS_SUCCESS = 'JOB_DETAILS_SUCCESS';
export const JOB_DETAILS_FAIL = 'JOB_DETAILS_FAIL';

export const COMMENTS_LIST_REQUEST = 'COMMENTS_LIST_REQUEST';
export const COMMENTS_LIST_SUCCESS = 'COMMENTS_LIST_SUCCESS';
export const COMMENTS_LIST_FAIL = 'COMMENTS_LIST_FAIL';

export const COMMENT_ADD_REQUEST = 'COMMENT_ADD_REQUEST';
export const COMMENT_ADD_SUCCESS = 'COMMENT_ADD_SUCCESS';
export const COMMENT_ADD_FAIL = 'COMMENT_ADD_FAIL';
export const COMMENT_DELETE_REQUEST = 'COMMENT_DELETE_REQUEST';
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS';
export const COMMENT_DELETE_FAIL = 'COMMENT_DELETE_FAIL';

export const JOB_CREATE_REQUEST = 'JOB_CREATE_REQUEST';
export const JOB_CREATE_SUCCESS = 'JOB_CREATE_SUCCESS';
export const JOB_CREATE_FAIL = 'JOB_CREATE_FAIL';
export const JOB_CREATE_RESET = 'JOB_CREATE_RESET';