export const WORKER_PROFILE_UPDATE_REQUEST = 'WORKER_PROFILE_UPDATE_REQUEST';
export const WORKER_PROFILE_UPDATE_SUCCESS = 'WORKER_PROFILE_UPDATE_SUCCESS';
export const WORKER_PROFILE_UPDATE_FAIL = 'WORKER_PROFILE_UPDATE_FAIL';

export const WORKER_PROFILE_DETAILS_REQUEST = 'WORKER_PROFILE_DETAILS_REQUEST';
export const WORKER_PROFILE_DETAILS_SUCCESS = 'WORKER_PROFILE_DETAILS_SUCCESS';
export const WORKER_PROFILE_DETAILS_FAIL = 'WORKER_PROFILE_DETAILS_FAIL';
