export const WORKER_DETAIL_REQUEST = 'WORKER_DETAIL_REQUEST'
export const WORKER_DETAIL_SUCCESS = 'WORKER_DETAIL_SUCCESS'
export const WORKER_DETAIL_FAIL = 'WORKER_DETAIL_FAIL'

/* CONSTANTS USED IN Review creation */
export const WORKER_CREATE_REVIEW_REQUEST = "WORKER_CREATE_REVIEW_REQUEST";
export const WORKER_CREATE_REVIEW_SUCCESS = "WORKER_CREATE_REVIEW_SUCCESS";
export const WORKER_CREATE_REVIEW_FAIL = "WORKER_CREATE_REVIEW_FAIL";
export const WORKER_CREATE_REVIEW_RESET = "WORKER_CREATE_REVIEW_RESET";